<!DOCTYPE html>
<html>

<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Wilcoxon Signed Rank Statistic</title>

    
    <link href="../../../css/common.css" rel="stylesheet" type="text/css">
    
    
    
    <script src="/jsscripts/siteanalytics.js"></script>

</head>









<body>
<?php
    $mainmenuloc = $_SERVER["DOCUMENT_ROOT"]."/mainmenu.php"; 
    include $mainmenuloc;
?>


<h1>Wilcoxon Signed Rank Statistic</h1>


<img src="../images/dist_wilcox_signrank_pw.png" alt=""/>
    

<p>&nbsp;</p>

<h3> Arguments</h3>
<table class="funcarguments">
    <tr>
        <td>x:</td>
        <td>quantile, number / Vector</td>
    </tr>
    <tr>
        <td>p:</td>
        <td>Cumulative probability</td>
    </tr>
    <tr>
        <td>q:</td>
        <td>quantile, number / Vector</td>
    </tr>
    <tr>
        <td>n:</td>
        <td>Sample size</td>
    </tr>
</table>







<p>&nbsp;</p>
<p>&nbsp;</p>








<!-- ***************************************************************** -->


<h2 id="dsignrank">dsignrank</h2>
<p>Computes the probability. </p>

<p class="funcsignature">
    
    dsignrank{x=, n=} &rarr; Vector / number<br>
    
    <br>
    
    dsignrank(x=, n=) &rarr; Vector / number
   
</p>


<p>
    <em>Note:</em> If the argument x is greater than the number of coefficients 
    generated by argument n, or if x&lt;0, the function returns 0.0. 
</p>

<p>&nbsp;</p>

<p class="CodeCommand">
    &gt;&gt;std.dsignrank{x=2, n=4} <br />
    0.0625	<br />

    <br />

    &gt;&gt;std.dsignrank(2,4) <br />
    0.0625	<br />

    <br />

    &gt;&gt;v=std.tovector{2, 3} <br />
    &gt;&gt;std.dsignrank{x=v, n=4} <br />
    0.0625&nbsp;&nbsp;&nbsp;&nbsp; 0.125&nbsp;&nbsp;&nbsp;&nbsp; COL
</p>


<p>&nbsp;</p>

<div>
    <p>Mathematically:</p>
    
    <img src="../images/dist_wilcoxsignrank_mw_closed.png" alt=""/> <br />
    <img alt="" src="../images/dist_wilcoxsignrank_mw_open.png" />

    <p>
        For x=2, the coefficient of e<sup>2t</sup> is 1. Therefore 1/16=0.0625. <br />
        For x=3, the coefficient of e<sup>3t</sup> is 2. Therefore 2/16=0.125.
    </p>
</div>










<p>&nbsp;</p>
<p>&nbsp;</p>










<!-- ***************************************************************** -->

<h2 id="psignrank">psignrank</h2>
<p>Computes the cumulative probability. </p>

<p class="funcsignature">
    
    psignrank{q=, n=} &rarr; Vector / number<br>
    
    <br>
    
    psignrank(q=, n=) &rarr; Vector / number
   
</p>

<p>
    Note: If argument <em>q</em> is not an integer number, then it is rounded to the nearest integer number.
</p>



<p class="CodeCommand">
    &gt;&gt;std.psignrank{q=2, n=4} <br />
    0.1875	<br />

    <br />

    &gt;&gt;std.psignrank{q=3, n=4} <br />
    0.3125	<br />

    <br />
    <br />

    &gt;&gt;std.psignrank{q=2.4, n=4} <span class="LuaComment">--rounded to 2</span> <br />
    0.1875	<br />

    <br />

    &gt;&gt;std.psignrank{q=2.6, n=4} <span class="LuaComment">--rounded to 3</span> <br />
    0.3125	
</p>










<p>&nbsp;</p>
<p>&nbsp;</p>









<!-- ***************************************************************** -->

<h2 id="qsignrank">qsignrank</h2>
<p>Computes the quantile. </p>

<p class="funcsignature">
    
    qsignrank{p=, n=} &rarr; Vector / number<br>
    
    <br>
    
    qsignrank(p=, n=) &rarr; Vector / number
   
</p>

<p>
    <em>Note: </em>The function rounds up the result.
</p>

<p class="CodeCommand">
    &gt;&gt;std.<mark>p</mark>signrank{q=2, n=4} <br />
    0.1875 <br />

    <br />
    <br />

    &gt;&gt;std.qsignrank{p=0.18, n=4} <br />
    2	<br />

    <br />

    &gt;&gt;std.qsignrank{p=0.1876, n=4} <br />
    3	
</p>








<p>&nbsp;</p>
<p>&nbsp;</p>









<div class="RelatedLinks">
    <a href="dist_binom.php">Binomial Dist</a>
    <a href="dist_unif.php">Uniform Dist</a>
    <a href="dist_pois.php">Poisson Dist</a>
    <a href="dist_norm.php">Normal Dist</a>
    <a href="dist_chisq.php">Chi-Square Dist</a>
    <a href="dist_t.php">t Dist</a>
    <a href="dist_f.php">F Dist</a>
</div>
    
</body>

</html>
