<!DOCTYPE html>
<html>

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>skew</title>


    <link href="../../../css/common.css" rel="stylesheet" type="text/css" />

</head>

<body>
<?php
    $mainmenuloc = $_SERVER["DOCUMENT_ROOT"]."/mainmenu.php"; 
    include $mainmenuloc;
?>


<h1>skew</h1>

<p>Computes the skewness of a distribution</p>
<p class="funcsignature">
    skew(v) &rarr; number   
</p>

<p>where argument v is of type Vector.</p>

<p>&nbsp;</p>

<p>
    <em>Example #1:</em> Compute the skewness of a data set generated by
    <a href="dist_norm.php#rnorm">rnorm</a> function.
</p>

<p class="CodeCommand">
    &gt;&gt;v=std.rnorm(500) <br />

    <br />

    &gt;&gt;std.skew(v) <br />
    0.032
</p> 



<p>&nbsp;</p>



<p><em>Example #2:</em> Compute the skewness of a non-normally distributed data set.</p>

<p class="CodeCommand">
    &gt;&gt;v=std.rnorm(500)+std.runif(500) <br />

    <br />

    &gt;&gt;std.skew(v) <br />
    0.41
</p>


<p>&nbsp;</p>
<p>&nbsp;</p>

<div class="RelatedLinks">
    <a href="dist_unif.php#runif">runif</a>
    <a href="rand.php">rand</a>
    <a href="dist_norm.php#rnorm">rnorm</a>
    <a href="dist_pois.php#rpois">rpois</a>
</div>

</body>

</html>
